# Generated by Django 4.2.6 on 2023-10-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(default=1, upload_to='animal_images/'),
            preserve_default=False,
        ),
    ]
